
###
http://127.0.0.1:3000/allbuyers

###
POST http://127.0.0.1:3000/buyerdetails
Content-Type: application/json

{"data": "f9c69ac7"}

###
POST http://127.0.0.1:3000/allbydate
Content-Type: application/json

{"data": "1596240000"}
