
https://kqxty15mpg.execute-api.us-east-1.amazonaws.com/transactions

###

http://127.0.0.1:3000/buyers

###

http://127.0.0.1:3000/products


###

http://127.0.0.1:3000/transactions

###
http://127.0.0.1:8080
